In [1]:
#pip install xgboost lightgbm catboost pandas scikit-learn

In [2]:
import pandas as pd
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split

In [27]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix

In [5]:
df = pd.read_csv('C:/Users/User/FOR ML learnin stepik/TITANIK LEARN/train.csv')

In [6]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df = df.drop('Cabin', axis=1)
## Удалить колонку 'Age' (создаёт новый DataFrame, если не указать inplace=True)
##df = df.drop('Age', axis=1)

# Или более явно с параметром columns
##df = df.drop(columns=['Age'])

# Удалить несколько колонок сразу
##df = df.drop(columns=['Age', 'Cabin', 'Ticket'])

# Удалить, изменяя исходный DataFrame (inplace=True)
##df.drop('Age', axis=1, inplace=True)

In [9]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [10]:
df = df.dropna(subset = ['Embarked'])

In [11]:
maen_age = df['Age'].mean()
df['Age'].fillna(maen_age, inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_36516\1274005726.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(maen_age, inplace = True)
C:\Users\User\AppData\Local\Temp\ipykernel_36516\1274005726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'].fillna(maen_age, inplace = True)

In [12]:
df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

     Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0         3    male  22.000000      1      0   7.2500        S
1         1  female  38.000000      1      0  71.2833        C
2         3  female  26.000000      0      0   7.9250        S
3         1  female  35.000000      1      0  53.1000        S
4         3    male  35.000000      0      0   8.0500        S
..      ...     ...        ...    ...    ...      ...      ...
886       2    male  27.000000      0      0  13.0000        S
887       1  female  19.000000      0      0  30.0000        S
888       3  female  29.642093      1      2  23.4500        S
889       1    male  26.000000      0      0  30.0000        C
890       3    male  32.000000      0      0   7.7500        Q

[889 rows x 7 columns]

In [13]:
X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

In [14]:
y = df['Survived']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
# CatBoost вообще не требует предобработки — передаём данные как есть, только укажем, какие признаки категориальные.

In [17]:
from catboost import CatBoostClassifier

In [18]:
# CatBoost сам поймёт категории, если тип данных 'object' или 'category', но лучше явно указать
X_train_cat = X_train.copy()
X_test_cat = X_test.copy()

In [19]:
# Заполним пропуски (CatBoost умеет с ними работать, но для чистоты эксперимента заполним)
X_train_cat['Age'] = X_train_cat['Age'].fillna(X_train_cat['Age'].mean())
X_test_cat['Age'] = X_test_cat['Age'].fillna(X_train_cat['Age'].mean())

In [20]:
# Укажем имена категориальных колонок
cat_features = ['Sex', 'Embarked']

In [21]:
model_cat = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=3, random_seed=42, verbose=False)
model_cat.fit(X_train_cat, y_train, cat_features=cat_features)

CatBoostClassifier(depth=3, iterations=100, learning_rate=0.1, random_seed=42, verbose=False)

In [22]:
y_pred_cat = model_cat.predict(X_test_cat)
print("CatBoost Accuracy:", accuracy_score(y_test, y_pred_cat))

CatBoost Accuracy: 0.8314606741573034

In [23]:
print("CatBoost F1:", f1_score(y_test, y_pred_cat))

CatBoost F1: 0.7857142857142857

In [24]:
print("CatBoost roc_auc:", roc_auc_score(y_test, y_pred_cat))

CatBoost roc_auc: 0.8251562292248371

In [25]:
print("CatBoost precision:", precision_score(y_test, y_pred_cat))

CatBoost precision: 0.7746478873239436

In [26]:
print("CatBoost recall:", recall_score(y_test, y_pred_cat))

CatBoost recall: 0.7971014492753623

In [28]:
print("CatBoost confusion_matrix:", confusion_matrix(y_test, y_pred_cat))

CatBoost confusion_matrix: [[93 16]
 [14 55]]